FROM ubuntu:latest

# get list of installable packets and install wget
RUN apt-get update && apt-get -y install 'wget'
RUN apt-get install unzip
# install python/python-pip for web application
RUN apt-get install python3-pip -y

COPY . /web
WORKDIR /web

# download snap installer version 8.0
RUN wget http://step.esa.int/downloads/8.0/installers/esa-snap_sentinel_unix_8_0.sh
#change file execution rights for snap installer
RUN chmod +x esa-snap_sentinel_unix_8_0.sh
# install snap with gpt
RUN ./esa-snap_sentinel_unix_8_0.sh -q
# remove the .sh file
RUN rm ./esa-snap_sentinel_unix_8_0.sh
# link gpt so it can be used systemwide
RUN ln -s /usr/local/snap/bin/gpt /usr/bin/gpt
# set gpt max memory to 4GB
RUN sed -i -e 's/-Xmx1G/-Xmx4G/g' /usr/local/snap/bin/gpt.vmoptions




RUN pip install -r requirements.txt
#RUN mkdir downloaded_data
ENTRYPOINT ["python3"]
CMD ["app.py"]