FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install python3-pip -y
COPY . /web
WORKDIR /web
RUN pip install -r requirements.txt
RUN mkdir downloaded_data
ENTRYPOINT ["python3"]
CMD ["app.py"]